### ISSUE TITLE
Roadmap v0.1

### ISSUE THREAD

**Issue by nzain** [ixmilia/converters#1]
This issue shall kick off discussions & brainstorming about potential features and hopefully allows to create an intuitive and consistent API from the very start. This may include crazy-complex features that will never make it into this project, but its healthy for the API to think about them, at least.

Lets start with low hanging fruits (or maybe not) for the first version v0.1 (?) :

- [x] Convert all line drawings from DXF object to a PDF object.
- [x] Convert arcs and polylines.
- [ ] Convert style properties (color, thickness, what else?). Color mapping might not be a simple as it sounds, since the DXF colormap depends on the viewer, if I rember correctly.

Future

- Support more DXF objects. Some objects might be terribly complex if PDF doesn't support them directly (splines?).
- Source area selection: package consumers might know / select a region of interest that should be converted. Use case from my side: Din A4 DXF template is filled with customer data and should be printable 1:1, i.e. converted to a DinA4 PDF page.
- Target area selection: The output size could be automatic, letter, DinA4, whatever.
- Embedd DXF (or even partial) into existing PDF object? Think of MS Word and image insertion.
- Clipping of source objects
- Unicode support on PDF side https://github.com/ixmilia/pdf/issues/1
- API sugar: convert filen to file.

Looking forward to hear your thoughts!

**Comment by nzain** [comment]
Basic color support is implemented in eeed69faee59c7eb3aab1734fd8dab227d5d52a0.

I have no idea how to convert `DxfLineWeight` (just a `short`) to a meaningful PDF unit. Any idea?

Some more interesting entities (`DxfCircle`, `DxfArc`, `DxfLwPolyline` including bulge) are now supported with cfcaff676dcebc5b9c27ab0ec1aa06dca974b207.

I realized that line endings (LineCap) are always squared and some polylines look quite ugly:
![image](https://user-images.githubusercontent.com/13961979/69068867-d0b7de00-0a25-11ea-8436-c3b4f5adc80a.png)
The green one is just multiple straight segments, the red one contains arc segments.

**Comment by brettfo** [comment]
Instead of line weight, use the `Thickness` property which is a `double`.  The [DXF spec](http://help.autodesk.com/view/OARX/2020/ENU/?guid=GUID-3610039E-27D1-4E23-B6D3-7E60B22BB5BD) states that the line weight (scroll down to code `370`) is an enum value, but I don't know what those enum values are.

Most entities, however, have a `Thickness` property ([here](http://help.autodesk.com/view/OARX/2020/ENU/?guid=GUID-FCEF5726-53AE-4C43-B4EA-C84EB8686A66) for `LINE`) which should be in the default drawing units.

**Comment by nzain** [comment]
The `LineWeightEnum` is the only thing you can specify for a layer, which is what we/our customers usually do. You're right, all geometric entities seem to have a `Thickness`, but as far as my QCad tests go, this value is always zero. Setting a line's width to explicit 1mm, the short value becomes 100, but Thickness remains zero.

I've added initial text support as well, but it doesn't look very similar to the original DXF. Now font dictionaries, font size, vertical and horizontal alignment come into play. Not to mention encoding, which is really too far away right now. You won't find any unit tests, since I don't know what to expect... my PDF application is my terrible test.

**Comment by brettfo** [comment]
I've been looking through the DXF spec and may have an answer about `DxfLineWeight`.  While the line weight value listed for `LAYER` doesn't give any details, there is more information in the header that may be relevant.  Check [here](http://help.autodesk.com/view/OARX/2020/ENU/?guid=GUID-A85E8E67-27CD-4C59-BE61-4DC9FADBE74A) under the variables `$DIMLWD` and `$DIMLWE `.  According to that a non-zero number represents 1/100th of a mm which explains your case of `100` => 1mm.

Edit: added a doc comment in ixmilia/dxf [here](https://github.com/ixmilia/dxf/commit/3f9542ecbdfde6de94ff044566aa6dbd24886dc1).
